# Site
repository: ocollp/ocollp.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Olga Coll
title: Engineering Lead and Backend Developer
email: olgacollperez@gmail.com
# website: www.github.com/ocollp/test

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ocollp
github_username:  ocollp
linkedin_username: ocollp

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced Engineering Lead with a track record of managing and mentoring high-performing teams to deliver technical solutions aligned with architectural standards. Skilled in balancing feature delivery and technical debt, I excel in creating personalized growth plans for teams members and ensuring stakeholder needs are met. Known for effectively measuring progress and communicating to drive team success, with an extensive background in infrastructure, CI/CD, and QA processes. Demonstrated a strong track record in designing and implementing automated pipelines, optimizing deployment workflows, and enforcing rigorous quality assurance practices to ensure high reliability and performance.
  
content:
  - title: Experience
    layout: list 
    content:
      - layout: left
        title: wefox
        link: wefox.com
        link_text: wefox.com
        sub_title: Engineering Lead
        caption: Sep 2022 - Present
        description: |
          I am responsible for overseeing both the management of the individuals within my squad, as well as the technical delivery of our goals. This includes ensuring that my team has the resources they need to be successful, while also making certain that we are delivering high-quality solutions that meet our stakeholders' needs.
      - layout: left
        title: wefox
        link: wefox.com
        link_text: wefox.com
        sub_title: Java Developer
        caption: Nov 2018 - Sep 2022
        description: |
          I was responsible for writing high-quality and efficient code that adhered to best practices. I took pride in ensuring that my code was well-organized, readable, and maintainable, and I always made sure to apply rigorous testing to ensure its functionality.

          Whether I was working on new features, fixing bugs or optimizing existing systems, I was always focused on delivering the best possible results, working closely with other team members to achieve our goals. I was dedicated to delivering high-quality software that met the needs of our customers and exceeded their expectations.
      - layout: left
        title: NTT Data
        link: nttdata.com
        link_text: nttdata.com
        sub_title: Junior Java Developer
        caption: Jul 2017 - Nov 2018
        description: |
          As a junior backend developer, my main responsibilities were to develop new features, resolve bugs and improve the code. I was encouraged to maintain a high level of code quality and worked closely with my team to understand the full scope of the project.
      - layout: left
        title: DEIdeas Marketing Solutions
        link: deideasmarketing.com
        link_text: deideasmarketing.com
        sub_title: Junior Software Developer
        caption: Jan 2017 - Jul 2017
        description: |  
          During my internship, I had the opportunity to work on developing hybrid mobile applications using the Ionic Framework and native Android. With the guidance of my mentor, I was able to gain valuable hands-on experience and contribute to the development of applications for two different projects.
  
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed